name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pycodestyle pyleri
          pip install -r requirements.txt

      - name: Install and configure snmp
        run: |
          sudo apt-get install -y snmpd
          echo 'createUser user_md5_des MD5 password DES password' | sudo tee -a /etc/snmp/snmpd.conf
          echo 'rwuser user_md5_des priv' | sudo tee -a /etc/snmp/snmpd.conf
          sudo service snmpd restart
      - name: Run unittests
        run: |
          pytest
      - name: Lint with PyCodeStyle
        run: |
          find . -name \*.py -exec pycodestyle --ignore=E501 {} +
